In [7]:
from pathlib import Path

import pandas as pd

from plant_shape_analysis.data_preprocessing.process_gt_TrackPlant3D  import custom_trimmed_poisson

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Get GT data

We review the manual quality assesment of the dense point cloud data to only compute traits for the good leaves for now

In [13]:
base_path = Path("../data/TrackPlant3D")
qa_csv = base_path / "dense_leaves" / "dense_leaves_quality_assesment.csv"
df = pd.read_csv(qa_csv, delimiter=';')
df.head(n=20)

,dense_leaf_id,leaf_sequence_id,file_name,crop,treatment,plant,day,leaf,quality,comment
0,0,0,1_maize_control_plant1_D00_leaf1_dense,maize,control,1,0,1,good,NaN
1,1,1,1_maize_control_plant1_D00_leaf2_dense,maize,control,1,0,2,bad,large holes
2,2,0,2_maize_control_plant1_D01_leaf1_dense,maize,control,1,1,1,good,NaN
3,3,1,2_maize_control_plant1_D01_leaf2_dense,maize,control,1,1,2,bad,poor segmentation
4,4,0,3_maize_control_plant1_D02_leaf1_dense,maize,control,1,2,1,good,NaN
5,5,1,3_maize_control_plant1_D02_leaf2_dense,maize,control,1,2,2,regular,poor segmentation
6,6,2,3_maize_control_plant1_D02_leaf3_dense,maize,control,1,2,3,regular,large noise - remove manually
7,7,0,4_maize_control_plant1_D03_leaf1_dense,maize,control,1,3,1,good,NaN
8,8,1,4_maize_control_plant1_D03_leaf2_dense,maize,control,1,3,2,good,NaN
9,9,2,4_maize_control_plant1_D03_leaf3_dense,maize,control,1,3,3,regular,missing chunk
10,10,0,5_maize_control_plant1_D04_leaf1_dense,maize,control,1,4,1,good,NaN
11,11,1,5_maize_control_plant1_D04_leaf2_dense,maize,control,1,4,2,good,NaN
12,12,2,5_maize_control_plant1_D04_leaf3_dense,maize,control,1,4,3,good,"small noise - apply SOR(nb=50,std=10)"
13,13,0,6_maize_control_plant1_D05_leaf1_dense,maize,control,1,5,1,good,NaN
14,14,1,6_maize_control_plant1_D05_leaf2_dense,maize,control,1,5,2,good,"small noise - apply SOR(nb=20,std=15)"
15,15,2,6_maize_control_plant1_D05_leaf3_dense,maize,control,1,5,3,good,"small noise - apply SOR(nb=50,std=12)"
16,16,0,7_maize_control_plant1_D06_leaf1_dense,maize,control,1,6,1,good,NaN
17,17,1,7_maize_control_plant1_D06_leaf2_dense,maize,control,1,6,2,regular,large holes
18,18,2,7_maize_control_plant1_D06_leaf3_dense,maize,control,1,6,3,bad,large holes / poor segmentation
19,19,0,8_maize_control_plant1_D07_leaf1_dense,maize,control,1,7,1,bad,large holes / noise

In [21]:
good_leaves = df.loc[df['quality'] == 'good'].reset_index(drop=True)
good_leaves

,dense_leaf_id,leaf_sequence_id,file_name,crop,treatment,plant,day,leaf,quality,comment
0,0,0,1_maize_control_plant1_D00_leaf1_dense,maize,control,1,0,1,good,NaN
1,2,0,2_maize_control_plant1_D01_leaf1_dense,maize,control,1,1,1,good,NaN
2,4,0,3_maize_control_plant1_D02_leaf1_dense,maize,control,1,2,1,good,NaN
3,7,0,4_maize_control_plant1_D03_leaf1_dense,maize,control,1,3,1,good,NaN
4,8,1,4_maize_control_plant1_D03_leaf2_dense,maize,control,1,3,2,good,NaN
5,10,0,5_maize_control_plant1_D04_leaf1_dense,maize,control,1,4,1,good,NaN
6,11,1,5_maize_control_plant1_D04_leaf2_dense,maize,control,1,4,2,good,NaN
7,12,2,5_maize_control_plant1_D04_leaf3_dense,maize,control,1,4,3,good,"small noise - apply SOR(nb=50,std=10)"
8,13,0,6_maize_control_plant1_D05_leaf1_dense,maize,control,1,5,1,good,NaN
9,14,1,6_maize_control_plant1_D05_leaf2_dense,maize,control,1,5,2,good,"small noise - apply SOR(nb=20,std=15)"
10,15,2,6_maize_control_plant1_D05_leaf3_dense,maize,control,1,5,3,good,"small noise - apply SOR(nb=50,std=12)"
11,16,0,7_maize_control_plant1_D06_leaf1_dense,maize,control,1,6,1,good,NaN
12,25,2,9_maize_control_plant1_D08_leaf3_dense,maize,control,1,8,3,good,NaN
13,26,3,9_maize_control_plant1_D08_leaf4_dense,maize,control,1,8,4,good,"outliers - apply SOR(nb=50,std=10)"
14,27,4,10_maize_control_plant2_D00_leaf1_dense,maize,control,2,0,1,good,"outliers - apply SOR(nb=50,std=5)"
15,33,4,12_maize_control_plant2_D02_leaf1_dense,maize,control,2,2,1,good,small holes
16,34,5,12_maize_control_plant2_D02_leaf2_dense,maize,control,2,2,2,good,small holes
17,35,6,12_maize_control_plant2_D02_leaf3_dense,maize,control,2,2,3,good,small noise
18,37,4,13_maize_control_plant2_D03_leaf1_dense,maize,control,2,3,1,good,NaN
19,38,5,13_maize_control_plant2_D03_leaf2_dense,maize,control,2,3,2,good,"small noise - apply SOR(nb=50,std=10) / poor s..."
20,42,5,14_maize_control_plant2_D04_leaf2_dense,maize,control,2,4,2,good,NaN
21,44,7,14_maize_control_plant2_D04_leaf4_dense,maize,control,2,4,4,good,poor segmentation - correct manually / small n...
22,50,5,16_maize_control_plant2_D06_leaf2_dense,maize,control,2,6,2,good,NaN
23,51,6,16_maize_control_plant2_D06_leaf3_dense,maize,control,2,6,3,good,small holes
24,53,4,17_maize_control_plant2_D07_leaf1_dense,maize,control,2,7,1,good,small holes - check mesh
25,54,5,17_maize_control_plant2_D07_leaf2_dense,maize,control,2,7,2,good,small noise
26,55,6,17_maize_control_plant2_D07_leaf3_dense,maize,control,2,7,3,good,"small noise - apply SOR(nb=50,std=10) - correc..."
27,56,7,17_maize_control_plant2_D07_leaf4_dense,maize,control,2,7,4,good,"small noise - apply SOR(nb=50,std=10) - correc..."
28,57,8,17_maize_control_plant2_D07_leaf5_dense,maize,control,2,7,5,good,"small noise - apply SOR(nb=50,std=10) - correc..."
29,58,4,18_maize_control_plant2_D08_leaf1_dense,maize,control,2,8,1,good,NaN
30,59,5,18_maize_control_plant2_D08_leaf2_dense,maize,control,2,8,2,good,"small noise - apply SOR(nb=50,std=8)"
31,60,6,18_maize_control_plant2_D08_leaf3_dense,maize,control,2,8,3,good,"small noise - apply SOR(nb=50,std=10)"

In [29]:
good_leaves.groupby('leaf_sequence_id').agg(count=('dense_leaf_id', 'count')).reset_index()

   leaf_sequence_id  count
0                 0      7
1                 1      3
2                 2      3
3                 3      1
4                 4      5
5                 5      6
6                 6      4
7                 7      2
8                 8      1